### ISSUE TITLE
Enhancement Include Geo Location in Exif

### ISSUE THREAD

**Issue by aftabsikander** [sandrios/sandriosCamera#8]
**Feature Request**

- I have test your library with different devices, I have observed exif information is preserved when saving image. I would like if you can include Geo tag information as well just like default camera application does, If location is on "They include Geo tag information in exif, If location service is disabled Geo tag information is null.

- Include Location permission to accommodate Geo location exif tag 

![screenshot_2017-01-20-15-04-04](https://cloud.githubusercontent.com/assets/4800511/22281601/9ed6409e-e2f9-11e6-89fa-33d9e09f63e4.png)

**Comment by arpitgandhi9** [comment]
@aftabsikander Adding location permission to library might not be a good option for everyone, since most apps may not require this functionality and hence asking for the permission from the users is unnecessarily.

What you can do is before launching the library, asking for permission from your app. For this you can use TedPermission since it is already a dependency of the library.
